name: sqflite_ffi
homepage: https://github.com/tekartik/sqflite/tree/master/packages_flutter/sqflite_ffi
description: sqflite ffi based implementation for flutter, sharing the sqflite isolate between isolates using IsolateNameServer.
version: 0.1.0
funding:
  - https://github.com/sponsors/alextekartik

topics:
  - sql
  - database

environment:
  sdk: ^3.12.0
  flutter: ">=3.44.0"

# This package supports all platforms listed below.
platforms:
  linux:
  macos:
  windows:
  android:
  ios:

dependencies:
  flutter:
    sdk: flutter
  sqflite_common_ffi: ">=2.4.2 <4.0.0"

dev_dependencies:
  flutter_lints: ">=6.0.0"
  flutter_test:
    sdk: flutter
  path:

flutter:
  plugin:
    platforms:
      android:
        dartPluginClass: SqfliteFfiPlugin
      ios:
        dartPluginClass: SqfliteFfiPlugin
      linux:
        dartPluginClass: SqfliteFfiPlugin
      macos:
        dartPluginClass: SqfliteFfiPlugin
      windows:
        dartPluginClass: SqfliteFfiPlugin

